image: registry.gitlab.com/denrask/opentap-apitest:tap

variables:
  PACKAGE_REPO_URL: "http://packages.opentap.io"
  GIT_DEPTH: ""


stages:
  - build
  - package
  - publish


Test:
    stage: build
    tags:
        - gitlab-org
    script:
      - dotnet build
      - bin/Debug/tap unit-test run


Build:
    stage: build
    tags:
        - gitlab-org
    script: 
      - dotnet build WebApiTester -c Release 
    artifacts:
      paths:
        - "bin/Release/*"

Package:
    stage: package
    tags:
        - gitlab-org
    image: opentapio/opentap:9.15-slim-ubuntu18.04
    dependencies:
      - Build
    needs:
      - Build
    script:
      - cd bin/Release
      - tap package create package.xml
    artifacts:
      untracked: false
      expire_in: 7 days
      paths:
        - "bin/Release/WebApiTester*.TapPackage"

#IntegrationTest:
#    stage: integration-test
#    tags:
#        - gitlab-org
#    image: opentapio/opentap:9.15-slim-ubuntu18.04
#    dependencies:
#      - Package
#    needs:
#      - Package
#    script:
#      - cp bin/Release/WebApiTester*.TapPackage /opt/tap/WebApiTester.TapPackage
#      - cp IntegrationTest/Test.TapPlan /opt/tap/Test.TapPlan
#      - cd /opt/tap
#      - tap package install WebApiTester.TapPackage --non-interactive --dependencies
#      - tap run Test.TapPlan

Publish:
    stage: publish
    tags:
        - gitlab-org
    image: opentapio/opentap:9.15-slim-ubuntu18.04
    dependencies:
      - Build
      - Package
    needs:
      - Build
        - Package
    script:
      - cd bin/Release
      - ./tap package install -f PackagePublish --version beta
      - ./tap package publish -r http://packages.opentap.io -k $PUBLIC_REPO_PASS *.TapPackage
